#!/bin/env lua

local bits = io.open("bits.js"):read"*a"
os.remove("README.md")
local readme = io.open("README.md", "w")

for comment, fn in bits:gmatch"(/%*%*.-%*/)\n(function.-\n})" do
  --for line in comment:gmatch"\n%s+%*%s+([^\n]+)" do
  --  if line:match"^@" then break end
  --end
  readme:write("```js\n")
  readme:write(comment.."\n")
  readme:write(fn)
  readme:write("\n```\n")
  local tmpf = os.tmpname()
  local p = io.popen(("sh -c 'esbuild --minify > %s'"):format(tmpf), "w")
  p:write(fn)
  p:close()
  readme:write("```js\n")
  readme:write(io.open(tmpf):read"*a")
  readme:write("```\n")
  os.remove(tmpf)
end
