#!/bin/awk -f

BEGIN {
    save_rs = RS
    RS = "^$"
    getline content < "README.md"
    close(file)
    match(content, /^(.+tablestart\-\->).+(<!\-\-tablestop.+)$/, parts)
    RS = save_rs
    print parts[1]
    print "Name|Description"
    print "----|-----------"
}

/^\/\*\*/ { incomment = 1; n = 0; delete comment; getline; }
/\* @/ { incomment = 0; }
/\*\// { incomment = 0; }

incomment {
    match($0, / \* (.+)$/, a)
    comment[n] = a[1]
    n++
}

/^function/ {
    printf "|"
    match($0, /function (.+)\(/, a)
    printf "`" a[1] "`|"
    for (i = 0; i < n; i++) {
        printf comment[i] " "
    }
    print ""
}

END {
    print parts[2]
}
